# Generated by Django 2.2.6 on 2020-02-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ip',
            new_name='ip_list',
        ),
    ]
