# Generated by Django 2.2.6 on 2020-02-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200221_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
